compose-generator/compose-generator

- .goreleaser.yml
- Dockerfile
- install.bat
- install.nsi
- install.sh
- predefined-services/backend/spring-gradle/backend/Dockerfile
- predefined-services/backend/spring-gradle/config.json
- predefined-services/backend/spring-maven/backend/Dockerfile
- predefined-services/backend/spring-maven/config.json
- predefined-services/db-admin/phpmyadmin/config.json
- predefined-services/frontend/angular/config.json
- predefined-services/frontend/angular/frontend/Dockerfile
- src/commands/generate.go
- src/utils/tools.go
- toolbox/Dockerfile
- Use Alpine container for exampleAppInitCmds
- Only show question for db admin tool, if at least one db was selecte beforehand
- Add more customization to Spring services
- Internal code optimizations
> Use Docker container for exampleAppInitCmds

- predefined-services/frontend/react/README.md
- predefined-services/frontend/react/config.json
- predefined-services/frontend/react/frontend/Dockerfile
- predefined-services/frontend/react/service.yml
- src/commands/generate.go
- src/utils/tools.go
- toolbox/Dockerfile
- Add predefined React service
- Optimize toolbox performance
> Predefined service: React

- media/example-config.yml
- predefined-services/backend/spring-gradle/config.json
- predefined-services/backend/spring-gradle/service.yml
- predefined-services/backend/spring-maven/backend/Dockerfile
- predefined-services/backend/spring-maven/config.json
- predefined-services/backend/spring-maven/service.yml
- predefined-services/database/mysql/config.json
- predefined-services/database/mysql/service.yml
- predefined-services/db-admin/phpmyadmin/config.json
- predefined-services/db-admin/phpmyadmin/service.yml
- predefined-services/frontend/angular/config.json
- predefined-services/frontend/angular/service.yml
- predefined-services/frontend/react/config.json
- predefined-services/frontend/react/service.yml
- predefined-services/tls-helper/letsencrypt/config.json
- predefined-services/tls-helper/letsencrypt/service.yml
- src/commands/generate.go
- src/compose-generator.go
- src/model/generate-config.go
- Add flag `-c` or `--config` to the `generate` command to pass in a predefined configuration
- Bugfixes
- Predefined service template optimizations
> Support for CI config files

- predefined-services/frontend/vue/README.md
- predefined-services/frontend/vue/config.json
- predefined-services/frontend/vue/frontend/Dockerfile
- predefined-services/frontend/vue/service.yml
- toolbox/Dockerfile
Add predefined service template for VueJS
> Predefined service: Vue

- .gitignore
- predefined-services/backend/flask/README.md
- predefined-services/backend/flask/backend/Dockerfile
- predefined-services/backend/flask/backend/main.py
- predefined-services/backend/flask/config.json
- predefined-services/backend/flask/service.yml
- predefined-services/backend/spring-gradle/config.json
- src/utils/tools.go
- toolbox/Dockerfile
- Add Flask service
- Introduce caching mechanism for toolbox image
> Predefined service: Flask

- src/commands/add.go
- src/commands/generate.go
- src/commands/install.go
- src/commands/remove.go
- src/commands/template.go
- src/utils/tools.go
- Improve safety checks to consider all files
- Refactoring
- Code improvements
> Improve safety file checks

- .gitignore
- README.md
- docs/docs/install/npm.md
- package-lock.json
- package.json
- Add npm distribution option
- Add npm install option to docs
> NPM distribution option

- .github/scripts/service-validator/config-schema.py
- .github/scripts/service-validator/predefined-service-validator.py
- .github/scripts/service-validator/requirements.txt
- .github/scripts/service-validator/service-schema.py
- .github/workflows/ci.yml
- .github/workflows/service-validation.yml
- media/readme-dockerhub.md
- src/model/compose-file.go
- Add Python script for validating predefined services
- Add workflow for validation
> Service validator workflow

- predefined-services/backend/flask/service.yml
- predefined-services/backend/spring-gradle/service.yml
- predefined-services/backend/spring-maven/service.yml
- predefined-services/database/mysql/service.yml
- predefined-services/db-admin/phpmyadmin/service.yml
- predefined-services/frontend/angular/service.yml
- predefined-services/frontend/react/service.yml
- predefined-services/frontend/vue/service.yml
- predefined-services/proxy/nginx/service.yml
- predefined-services/tls-helper/letsencrypt/service.yml
- src/commands/generate.go
Support multiple services of one type
> Support multiple services of one type

- predefined-services/db-admin/adminer/config.json
- predefined-services/db-admin/phpmyadmin/config.json
- src/cmd/generate.go
- src/utils/questions.go
- src/utils/tools.go
- Add mechanism to avoid duplicate port assigment
- Code optimizations
- Appearance polished
> Avoid duplicate port assignment

- src/cmd/add.go
- src/cmd/generate.go
- src/cmd/install.go
- src/cmd/remove.go
- src/cmd/template.go
- src/parser/template_parser.go
- src/utils/questions.go
- src/utils/tools.go
Print more details whenever an error occurs
> Print more error details

- src/cmd/generate.go
Add mechanism to avoid duplicate volume assignments. Duplicate volumes are not forbidden, only the default value is to use different volumes
> Avoid duplicate volumes

- predefined-services/INSTRUCTIONS_HEADER.md
- predefined-services/database/mariadb/service.yml
- predefined-services/database/mysql/service.yml
- predefined-services/database/postgres/config.json
- predefined-services/database/postgres/service.yml
- predefined-services/frontend/gitea/README.md
- predefined-services/frontend/gitea/config.json
- predefined-services/frontend/gitea/service.yml
- src/cmd/generate.go
- src/parser/template_parser.go
- Add predefined service for Gitea
- Add instruction header file
> Predefined service: Gitea

- docs/docs/usage/generate.md
- src/cmd/generate.go
- Apply changes in generate command to the docs
- Code optimizations
> Extend docs

- predefined-services/database/mysql/service.yml
- predefined-services/database/postgres/config.json
- predefined-services/database/postgres/service.yml
- predefined-services/frontend/jira/README.md
- predefined-services/frontend/jira/config.json
- predefined-services/frontend/jira/environment.env
- predefined-services/frontend/jira/service.yml
- src/cmd/generate.go
Added predefined service template for Atlassian Jira
> Predefined service: Jira

- predefined-services/frontend/jira/README.md
- predefined-services/frontend/youtrack/README.md
- predefined-services/frontend/youtrack/config.json
- predefined-services/frontend/youtrack/service.yml
Added predefined service template for JetBrains YouTrack
> Predefined service: YouTrack

- predefined-services/frontend/jenkins/README.md
- predefined-services/frontend/jenkins/config.json
- predefined-services/frontend/jenkins/service.yml
Added predefined service template for Jenkins
> Predefined service: Jenkins

- predefined-services/backend/flask/config.json
- predefined-services/db-admin/pgadmin/config.json
- src/cmd/remove.go
- src/util/questions.go
- Fix network removal issue
- Refactoring
> Fix network issue on service removal

- predefined-services/database/cassandra/config.json
- predefined-services/database/cassandra/service.yml
- src/.gitignore
Added predefined service template for Apache Cassandra
> Predefined service: Cassandra

- .github/workflows/publish.yml
- .goreleaser.yml
- build.bat
- build.sh
- predefined-services/README.md
- Add support for Docker multi-arch images, including following architectures
- amd64
- i386
- armv6
- armv7
- Update publish workflow to build those multi-arch images for releases
- Extended documentation for contributing predefined service templates
> Add support for Docker multi-arch

- predefined-services/database/questdb/README.md
- predefined-services/database/questdb/config.json
- predefined-services/database/questdb/service.yml
- Add predefined service template for QuestDB
> Predefined service: QuestDB

- .github/workflows/misspell.yml
- predefined-services/frontend/grafana/README.md
- predefined-services/frontend/live-poll/README.md
- predefined-services/tls-helper/letsencrypt/config.json
- src/cmd/add.go
- src/util/cli_test.go
- Add workflow for detecting misspellings
- Fix misspellings
> Misspell workflow

- .github/dependabot.yml
- .github/workflows/publish.yml
- predefined-services/backend/django/config.json
- predefined-services/backend/php/config.json
- predefined-services/backend/prometheus/config.json
- predefined-services/backend/prometheus/service.yml
- predefined-services/backend/rails/config.json
- predefined-services/backend/rocket/config.json
- predefined-services/backend/spring-gradle/config.json
- predefined-services/backend/spring-maven/config.json
- predefined-services/backend/telegram-bot/backend/requirements.txt
- predefined-services/database/elasticsearch/config.json
- predefined-services/database/mongodb/config.json
- predefined-services/database/neo4j/config.json
- predefined-services/database/postgres/config.json
- predefined-services/database/questdb/config.json
- predefined-services/frontend/bitbucket/config.json
- predefined-services/frontend/gitea/config.json
- predefined-services/frontend/grafana/config.json
- predefined-services/frontend/jenkins/config.json
- predefined-services/frontend/jira/config.json
- predefined-services/frontend/nextcloud/config.json
- predefined-services/frontend/sonarqube/config.json
- predefined-services/frontend/wordpress/config.json
- predefined-services/frontend/youtrack/config.json
- Update service version
- Update Goreleaser action
- Add dependabot config for GH actions
- Add missing Prometheus network
- Fix copy/paste mistake
> Update service versions

- .github/workflows/publish.yml
- .github/workflows/test.yml
- src/cmd/generate.go
- src/model/predefined-template.go
- src/parser/template_parser.go
- src/pass/add_networks.go
- src/pass/add_networks_test.go
- src/pass/add_volumes.go
- src/pass/add_volumes_test.go
- src/pass/gen_choose_backends.go
- src/pass/gen_choose_backends_test.go
- src/pass/gen_choose_databases.go
- src/pass/gen_choose_databases_test.go
- src/pass/gen_choose_db_admin.go
- src/pass/gen_choose_db_admin_test.go
- src/pass/gen_choose_frontends.go
- src/pass/gen_choose_frontends_test.go
- src/pass/gen_choose_proxy.go
- src/pass/gen_choose_proxy_test.go
- src/pass/gen_choose_tls_helper.go
- src/pass/gen_choose_tls_helper_test.go
- src/pass/gen_generate.go
- src/pass/gen_load_config.go
- src/pass/gen_load_config_test.go
- src/pass/mock_functions.go
- src/pass/remove_dependencies_test.go
- src/util/conditions_test.go
- src/util/templates.go
- src/util/version_test.go
- Add more tests for passes
- Upgrade Goreleaser version
> Add tests for passes

- src/cmd/generate.go
- src/pass/gen_copy_volumes.go
- src/pass/gen_dendency_groups.go
- src/pass/gen_dependency_groups_test.go
- Add support for template groups
- Add tests for template groups
> Add support for template groups

- src/cmd/add.go
- src/cmd/generate.go
- src/cmd/remove.go
- src/cmd/template-load.go
- src/cmd/template-save.go
- src/model/cg-project.go
- src/model/generate-config.go
- src/model/predefined-template.go
- src/parser/template_parser.go
- src/pass/add_volumes_test.go
- src/pass/gen_generate_test.go
- src/pass/gen_secrets_test.go
- src/pass/remove_networks.go
- src/project/delete_options.go
- src/project/load.go
- src/project/load_options.go
- src/project/save_options.go
- src/util/questions.go
- src/util/templates.go
- src/util/validators.go
Apply Goreportcard suggestions
> Apply Goreportcard suggestions

- .github/workflows/docs.yml
- .github/workflows/publish.yml
- docs/docs/install/linux.md
- docs/docs/install/npm.md
- docs/docs/install/source.md
- docs/docs/install/windows.md
- docs/docs/intro.md
- docs/docs/quick-start.md
- media/example-config.yml
- Update screencast
- Finish quick start guide
- Text fixes
> Finish docs for first stable release

- .github/workflows/publish.yml
- .goreleaser.yml
- Adjust publish workflow to not push to Nexus on a pre-release
- Fix release footer
> Prepare for pre-release

- .github/workflows/docs.yml
- .github/workflows/publish.yml
- CODE_OF_CONDUCT.md
- docs/docs/install/linux.md
- predefined-services/backend/django/config.json
- predefined-services/backend/flask/config.json
- predefined-services/backend/telegram-bot/config.json
- predefined-services/database/cassandra/README.md
- predefined-services/db-admin/adminer/README.md
- predefined-services/db-admin/pgadmin/README.md
- predefined-services/db-admin/phpmyadmin/README.md
- predefined-services/frontend/angular/README.md
- predefined-services/frontend/nextcloud/README.md
- predefined-services/frontend/owncloud/README.md
- predefined-services/frontend/react/README.md
- predefined-services/frontend/vue/README.md
- predefined-services/frontend/wordpress/README.md
- predefined-services/proxy/nginx/README.md
- predefined-services/tls-helper/letsencrypt/README.md
- src/project/delete.go
- src/project/delete_test.go
- src/project/mock_functions.go
- src/util/env.go
- src/util/env_test.go
- src/util/mock_functions.go
- src/util/templates.go
- Add more READMEs for predefined service templates
- Add tarball to release packages
- Optimize predefined services release flow
- Fix Linux installation page in the docs
- Python version to 3.10
- Add more tests
> Apply test cycle feedback

- .github/scripts/service-tester/predefined-service-tester.py
- .github/workflows/publish.yml
- Fix CentOS and Fedora rpm repository deployment on publish
- Supress pull progress information of testing workflow
> Fix CentOS and Fedora repo deployment

- src/cmd/generate.go
- src/cmd/generate_test.go
- src/model/predefined-template.go
- src/pass/generate/gen_copy_volumes.go
- src/pass/generate/gen_copy_volumes_test.go
- src/pass/generate/gen_replace_placeholders.go
- src/pass/generate/gen_replace_placeholders_test.go
- Fix bug when having a custom value for a volume or build context path
- Code simplification
- Improve code style
- Adjust tests accordingly
> Fix copy bug with custom volume / build context dir

- src/pass/generate/gen_copy_volumes.go
- src/pass/generate/gen_copy_volumes_test.go
- src/pass/generate/gen_generate.go
- Fix automatic dependencies (`frontend` > `backend`, `backend` > `database`, `dbadmin` > `database`)
- Code improvements
> Fix auto dependencies

- docs/docs/quick-start.md
- docs/docs/usage/install.md
- docs/mkdocs.yml
- media/readme-dockerhub.md
Remove npm installation method temporarily
> Remove npm installation method temporarily

- .github/dependabot.yml
- media/readme-dockerhub.md
- src/cmd/mock_functions.go
- src/cmd/template-delete.go
- src/cmd/template-delete_test.go
- src/cmd/template-load.go
- src/cmd/template-load_test.go
- src/compose-generator.go
- Add command to delete custom templates ( `cg template delete [template-name]` )
- Tests
> Command to delete custom templates

- .goreleaser.yml
- bash_autocomplete.sh
- src/compose-generator.go
- Support for cli auto-completino
- Install it with `deb`, `rpm` and `apk` packages out of the box
> Add support for auto-completion

- .github/scripts/service-validator/config-schema.py
- predefined-services/backend/pi-hole/config.json
- predefined-services/db-admin/pgadmin/config.json
- src/model/predefined-template.go
- src/pass/generate/gen_choose_backends.go
- src/pass/generate/gen_choose_backends_test.go
- src/pass/generate/gen_choose_databases.go
- src/pass/generate/gen_choose_databases_test.go
- src/pass/generate/gen_choose_db_admin.go
- src/pass/generate/gen_choose_db_admin_test.go
- src/pass/generate/gen_choose_frontends.go
- src/pass/generate/gen_choose_frontends_test.go
- src/pass/generate/gen_secrets.go
- src/pass/generate/mock_functions.go
- src/util/mock_functions.go
- src/util/questions.go
- src/util/templates.go
- Add support for customizable secrets
- Adjust config validation schema
- Tests
> Add support for customizable secrets

- .github/ISSUE_TEMPLATE/bug_report.yml
- media/readme-dockerhub.md
- package-lock.json
- package.json
- Update version
- Update tags in Docker Hub Readme
> Prepare for release

- .github/ISSUE_TEMPLATE/bug_report.yml
- media/readme-dockerhub.md
- package-lock.json
- package.json
- src/pass/generate/gen_copy_volumes.go
Hotfix: Bug with bind volume paths on Windows
> Release of version 1.2.1

- predefined-services/backend/django/config.json
- predefined-services/backend/nexus/config.json
- predefined-services/backend/pi-hole/config.json
- predefined-services/backend/prometheus/config.json
- predefined-services/backend/rocket/config.json
- predefined-services/database/influxdb/config.json
- predefined-services/database/questdb/config.json
- predefined-services/database/scylladb/config.json
- predefined-services/frontend/gitlab/config.json
- predefined-services/frontend/grafana/config.json
- predefined-services/frontend/jupyter/config.json
- predefined-services/frontend/uptime-kuma/config.json
- predefined-services/frontend/youtrack/config.json
- predefined-services/proxy/traefik/config.json
Update service template versions
> Update service template versions

- predefined-services/proxy/traefik/README.md
Add password notice to Traefik template Readme
> Traefik template improvement

- src/cmd/template-load_test.go
> Fix template list

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/dependabot.yml
- README.md
- media/readme-dockerhub.md
- package-lock.json
- package.json
Apply documentation updates and version bumps
> Documentation updates

- .github/workflows/publish.yml
- .goreleaser.yml
- Apply Goreleaser update
- Add full changelog link to release changelog
> Goreleaser update

- .goreleaser.yml
- src/util/env.go
- src/util/env_test.go
- src/util/logging.go
Change logfile location from `/usr/lib/compose-generator/log` to `/var/log/compose-generator`
> Fix logfile location

- .github/workflows/docs.yml
- docs/mkdocs.yml
- Apply changes due to the upgrade to Material for Mkdocs 8.0.0
> Docs version migration

- src/project/load.go
- src/util/conditions.go
- src/util/conditions_test.go
- src/util/env.go
- src/util/env_test.go
Optimize performance of CCom by executing the compiler executable directly without hopping through the CCom cli
> Optimize CCom performance

- predefined-services/backend/django/config.json
- predefined-services/backend/minecraft-server/config.json
- predefined-services/backend/monica/config.json
- predefined-services/backend/nexus/config.json
- predefined-services/backend/node/config.json
- predefined-services/backend/php/config.json
- predefined-services/backend/pi-hole/config.json
- predefined-services/backend/plex/config.json
- predefined-services/backend/rails/config.json
- predefined-services/backend/rocket/config.json
- predefined-services/database/faunadb/config.json
- predefined-services/database/mariadb/config.json
- predefined-services/database/neo4j/config.json
- predefined-services/database/postgres/config.json
- predefined-services/frontend/bitbucket/config.json
- predefined-services/frontend/ghost/config.json
- predefined-services/frontend/gitlab/config.json
- predefined-services/frontend/grafana/config.json
- predefined-services/frontend/mediawiki/config.json
- predefined-services/frontend/nextcloud/config.json
- predefined-services/frontend/openproject/config.json
- predefined-services/frontend/sonarqube/config.json
- predefined-services/frontend/uptime-kuma/config.json
- predefined-services/frontend/youtrack/config.json
Update dependency versions of:
- Django
- Minecraft Server
- Monica
- Nexus
- Node
- PHP
- Pihole
- Plex
- Rails
- Rocket
- FaunaDB
- MariaDB
- Neo4j
- Postgres
- BitBucket
- Ghost
- GitLab
- Grafana
- Mediawiki
- Nextcloud
- Open Project
- Sonatype
- Uptime Kuma
- YouTrack
> Update dependency versions

- .github/scripts/service-tester/predefined-service-tester.py
- .github/workflows/publish.yml
- .github/workflows/service-testing.yml
- Avoid to download toolbox image multiple times
- Do not prune images at all
- Optimize publish workflow
> Optimize tester script

- .github/scripts/service-tester/predefined-service-tester.py
- predefined-services/backend/spring-gradle/config.json
- predefined-services/backend/spring-maven/config.json
Update Spring version to 2.6.2
> Update Spring version

- .github/workflows/publish.yml
> Upgrade Goreleaser action

- .github/dependabot.yml
- .github/workflows/publish.yml
- .goreleaser.yml
- README.md
- media/readme-dockerhub.md
- package-lock.json
- package.json
> Prepare for update

- predefined-services/backend/adguard-home/config.json
- predefined-services/backend/django/config.json
- predefined-services/backend/nexus/config.json
- predefined-services/backend/node/config.json
- predefined-services/backend/pi-hole/config.json
- predefined-services/backend/plex/config.json
- predefined-services/backend/prometheus/config.json
- predefined-services/backend/rails/config.json
- predefined-services/database/elasticsearch/config.json
- predefined-services/database/faunadb/config.json
- predefined-services/database/scylladb/config.json
- predefined-services/frontend/bitbucket/config.json
- predefined-services/frontend/ghost/config.json
- predefined-services/frontend/gitlab/config.json
- predefined-services/frontend/grafana/config.json
- predefined-services/frontend/jira/config.json
- predefined-services/frontend/jupyter/config.json
- predefined-services/frontend/matomo/config.json
- predefined-services/frontend/sonarqube/config.json
- predefined-services/frontend/uptime-kuma/config.json
- predefined-services/frontend/youtrack/config.json
- predefined-services/proxy/traefik/config.json
> Update service templates

- predefined-services/backend/rails/backend-rails/Gemfile
- Align Rails dependency in Gemfile to the one, bundled into the toolbox
- Update other dependencies in Gemfile
> Fix Rails service template

- src/cmd/generate.go
- src/cmd/generate_test.go
- src/cmd/mock_functions.go
- src/cmd/template-delete.go
- src/model/predefined-template.go
- src/model/predefined-template_test.go
- src/parser/template_parser.go
- src/pass/generate/gen_add_proxy_networks.go
- src/pass/generate/gen_add_proxy_networks_test.go
- src/pass/generate/gen_add_watchtower.go
- src/pass/generate/gen_add_watchtower_test.go
- src/pass/generate/gen_choose_tls_helper.go
- src/pass/generate/gen_choose_tls_helper_test.go
- src/pass/generate/gen_dependency_groups.go
- src/pass/generate/gen_dependency_groups_test.go
- src/pass/generate/gen_generate.go
- src/pass/generate/gen_load_config.go
- src/pass/generate/gen_load_config_test.go
- src/pass/generate/mock_functions.go
- src/pass/install/install_docker_darwin.go
- src/pass/install/install_docker_darwin_test.go
- src/pass/install/install_docker_linux.go
- src/pass/install/install_docker_linux_test.go
- src/pass/install/install_docker_windows.go
- src/pass/install/install_docker_windows_test.go
- src/util/conditions.go
- src/util/conditions_test.go
- src/util/templates.go
- src/util/text.go
- src/util/text_test.go
Fix CI warnings regarding uncommented exposed functions and spelling improvements
> Fix ci warnings

- .github/workflows/publish.yml
Add support for Raspbian bullseye
> Add support for Raspbian bullseye

- docs/docs/install/linux.md
Fix installation command in docs for Raspbian
> Docs: Raspbian installation fix

- predefined-services/backend/rocket/backend-rocket/Dockerfile
> Fix Rocket template

- .github/workflows/publish.yml
- predefined-services/backend/adguard-home/config.json
- predefined-services/backend/django/config.json
- predefined-services/backend/nexus/config.json
- predefined-services/backend/node/config.json
- predefined-services/backend/pi-hole/config.json
- predefined-services/backend/plex/config.json
- predefined-services/backend/rails/config.json
- predefined-services/backend/rocket/config.json
- predefined-services/backend/spring-gradle/config.json
- predefined-services/backend/spring-maven/config.json
- predefined-services/database/elasticsearch/config.json
- predefined-services/database/faunadb/config.json
- predefined-services/database/influxdb/config.json
- predefined-services/database/neo4j/config.json
- predefined-services/database/scylladb/config.json
- predefined-services/frontend/gitlab/config.json
- predefined-services/frontend/grafana/config.json
- predefined-services/frontend/matomo/config.json
- predefined-services/frontend/uptime-kuma/config.json
- predefined-services/frontend/youtrack/config.json
- predefined-services/proxy/traefik/config.json
> Apply template updates

- src/cmd/cmd.go
- src/cmd/generate.go
- src/cmd/remove.go
- src/cmd/template-delete.go
- src/cmd/template-load.go
- src/cmd/template-save.go
> Improve cli help texts

- .github/ISSUE_TEMPLATE/service_suggestion.yml
Add an issue form for submitting predefined service suggestions
> Issue form for service suggestion

- .github/dependabot.yml
- .github/workflows/publish.yml
- .gitignore
- src/cmd/cmd.go
- src/compose-generator.go
- Improve cli help text
- Upgrade Goreleaser action
- Set core team as reviewer for dependabot prs
> Improve cli help text

- .github/workflows/publish.yml
- .github/workflows/test.yml
- Dependency upgrades for workflows
- Publish CG to WinGet repository with the publish workflow
> Workflow dependency upgrades

- predefined-services/proxy/nginx/config.json
- predefined-services/proxy/traefik/config.json
> Use Traefik as default proxy

- .github/dependabot.yml
- .github/workflows/winget-release.yml
- README.md
- media/readme-dockerhub.md
- package-lock.json
- package.json
> Prepare for next update

- src/go.mod
- src/go.sum
- src/vendor/github.com/compose-spec/compose-go/dotenv/godotenv.go
- src/vendor/github.com/compose-spec/compose-go/dotenv/parser.go
- src/vendor/github.com/compose-spec/compose-go/interpolation/interpolation.go
- src/vendor/github.com/compose-spec/compose-go/loader/full-example.yml
- src/vendor/github.com/compose-spec/compose-go/loader/loader.go
- src/vendor/github.com/compose-spec/compose-go/loader/merge.go
- src/vendor/github.com/compose-spec/compose-go/loader/validate.go
- src/vendor/github.com/compose-spec/compose-go/loader/windows_path.go
- src/vendor/github.com/compose-spec/compose-go/schema/compose-spec.json
- src/vendor/github.com/compose-spec/compose-go/template/template.go
- src/vendor/github.com/compose-spec/compose-go/types/project.go
- src/vendor/github.com/compose-spec/compose-go/types/types.go
- src/vendor/modules.txt
Fix bug, regarding templating incompatibility with the compose spec library
> Downgrade compose spec to fix bug
